### ISSUE TITLE
[Server] Client connections and INVALID_MESSAGE

### ISSUE THREAD

**Issue by dmeggyesy** [hjsong6230/COMP90015#9]
Our server does not handle clients sending INVALID_MESSAGE properly.
17:04:08.249 [Thread-4] DEBUG activitystreamer.server.ControlSolution {"command":"INVALID_MESSAGE","info":"die in a fire"}
17:04:08.251 [Thread-4] ERROR activitystreamer.server.ControlSolution die in a fire
Exception in thread "Thread-4" java.lang.NullPointerException
	at activitystreamer.server.ControlSolution.connectionClosed(ControlSolution.java:270)
	at activitystreamer.server.ControlSolution.process(ControlSolution.java:368)
	at activitystreamer.server.Connection.run(Connection.java:80)

**Comment by dmeggyesy** [comment]
Actually, it's *all* INVALID_MESSAGES, and potentially disconnects.

**Comment by dmeggyesy** [comment]
LOGOUT is fine
